#!/usr/bin/env python3
"""
Regenerate pregenerated Box3D bindings for boxddd-sys.

Usage:
  python tools/update_box3d_and_bindings.py
  python tools/update_box3d_and_bindings.py --mode both
  python tools/update_box3d_and_bindings.py --mode double --profile release
"""

import argparse
import os
import subprocess
import sys
from pathlib import Path
from typing import Optional


def run(cmd: list[str], cwd: Path, env: dict[str, str], dry_run: bool) -> int:
    print("$", " ".join(cmd))
    if dry_run:
        return 0
    try:
        subprocess.check_call(cmd, cwd=str(cwd), env=env)
        return 0
    except subprocess.CalledProcessError as exc:
        print(f"command failed ({exc.returncode}): {' '.join(cmd)}", file=sys.stderr)
        return exc.returncode


def find_bindings(target_dir: Path, profile: str) -> Optional[Path]:
    build_dir = target_dir / profile / "build"
    return max(
        build_dir.glob("boxddd-sys-*/out/bindings.rs"),
        key=lambda path: path.stat().st_mtime,
        default=None,
    )


def generate(repo_root: Path, mode: str, profile: str, dry_run: bool) -> int:
    env = os.environ.copy()
    env["BOXDDD_SYS_SKIP_CC"] = "1"
    env["BOXDDD_SYS_FORCE_BINDGEN"] = "1"
    profile_flag = ["--release"] if profile == "release" else []
    features = ["bindgen"] if mode == "default" else ["bindgen", "double-precision"]

    rc = run(
        [
            "cargo",
            "build",
            "-p",
            "boxddd-sys",
            "--features",
            ",".join(features),
            *profile_flag,
        ],
        cwd=repo_root,
        env=env,
        dry_run=dry_run,
    )
    if rc != 0:
        return rc

    target_dir = Path(env.get("CARGO_TARGET_DIR", repo_root / "target"))
    bindings = find_bindings(target_dir, profile)
    if bindings is None:
        print(f"generated bindings.rs not found under {target_dir / profile / 'build'}", file=sys.stderr)
        return 3

    crate_root = repo_root / "boxddd-sys"
    dest_name = "bindings_pregenerated.rs" if mode == "default" else "bindings_pregenerated_double.rs"
    dest = crate_root / "src" / dest_name
    header = (
        "// AUTOGENERATED: pregenerated Box3D bindings for docs.rs/offline builds\n"
        "// To refresh, run tools/update_box3d_and_bindings.py --mode "
        f"{mode}\n\n"
    )
    if not dry_run:
        content = bindings.read_text(encoding="utf-8", errors="ignore")
        dest.write_text(header + content, encoding="utf-8", newline="\n")
    print(f"updated {dest}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description="Regenerate pregenerated Box3D bindings")
    parser.add_argument("--mode", choices=["default", "double", "both"], default="default")
    parser.add_argument("--profile", choices=["debug", "release"], default="debug")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    repo_root = Path(__file__).resolve().parents[1]
    modes = ["default", "double"] if args.mode == "both" else [args.mode]
    for mode in modes:
        rc = generate(repo_root, mode, args.profile, args.dry_run)
        if rc != 0:
            return rc
    return 0


if __name__ == "__main__":
    sys.exit(main())
